id: P009511
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:35:43.632382
source_metadata:
  id: bdr:W1KG16578
  title: ལཉྪ་དང་ཝརྟུའི་ཕྱི་མོ་ཨུཏྤ་ལའི་འཕྲེང་རྒྱན།
  author: ''
  volumes:
    90ad2570bce64e8f9750e6dfaa7a4903:
      image_group_id: I2PD17881
      title: ''
      volume_number: 1
      total_pages: 122
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
